databases:
  - name: blurber
    databaseName: blurber
    user: blurber
    plan: free

services:
  - type: redis
    name: sidekiq-redis
    region: ohio
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: worker
    name: sidekiq-worker
    runtime: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        
  - type: web
    name: blurber
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "./bin/rails db:migrate db:seed" 
    startCommand: "./bin/rails server"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: blurber
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default