name: Run tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rails test
